### ISSUE TITLE
Slack workspaces are unusable within LibreRambox

### ISSUE THREAD

**Issue by bfc5288** [LibreRambox/LibreRambox#10]
### Steps to reproduce

1. Create/load a Slack workspace 

### Expected behavior
The Slack workspace loads normally.

### Actual behavior

I receive this message; when clicking `use Slack in your browser`, it tries loading then loops back to the same message:
```
Click "Open Slack" to launch the desktop app.
Not working? You can also use Slack in your browser.
```

I have tried restarting rambox, resetting the workspace within rambox, and restarting the computer. This issue affects all Slack workspaces in rambox; the workspaces work when loaded in a full browser.

This wasn't an issue around ~2 weeks ago; perhaps a Slack update caused this?

### ENVIRONMENT

> LibreRambox:
Version: 0.9.0
Platform: linux (x64)
Electron: 25.3.2
Chromium: 114.0.5735.248
Node: 18.15.0

> OS: Ubuntu 18.04

> Arch: x64

**Comment by wolfposd** [comment]
i just used the latest "nightly" build for 0.10.1  (see actions) , and followed these steps:


- start librerambox
- new service -> Slack -> put in URL -> click create
- in Slack-Tab -> enter email-address -> [sign in with email] -> put in code from email
- click on "use slack in my browser"

and it works fine

**Comment by bfc5288** [comment]
> i just used the latest "nightly" build for 0.10.1 ([1]) , and followed these steps:
> 
>     * start librerambox
> 
>     * new service -> Slack -> put in URL -> click create
> 
>     * in Slack-Tab -> enter email-address -> [sign in with email] -> put in code from email
> 
>     * click on "use slack in my browser"
> 
> 
> and it works fine
> 
> [1] https://github.com/LibreRambox/LibreRambox/actions/runs/6440679737

This works for me too, thank you for pointing me to the patch.

I wasn't aware that there were nightly builds for this app (of course, it's obvious after seeing the github actions and workflows...) so maybe it'd be nice if the use of nightly builds was mentioned in the README to make it clear that they're available.

**Comment by wolfposd** [comment]
ill update the readme
