### ISSUE TITLE
Slack no longer supported as of Oct 6th 2024

### ISSUE THREAD

**Issue by paoloantinori** [LibreRambox/LibreRambox#25]
https://slack.com/intl/en-gb/help/articles/115002037526-System-requirements-for-using-Slack#web-browser

At least from a headers pov, LibreRambox is presenting itself with an unsupported header.
Required `123`
In use: `117` 

https://github.com/LibreRambox/LibreRambox/blob/master/resources/services.json#L1197

### Steps to reproduce

1. 
2. 
3. 

### ENVIRONMENT

> LibreRambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by KevinRoebert** [comment]
@paoloantinori Created a PR. Can you confirm that it fixed the issue?

**Comment by KevinRoebert** [comment]
@paoloantinori You can download the builds from here: https://github.com/LibreRambox/LibreRambox/actions/runs/11233125028?pr=26 (login required)

**Comment by paoloantinori** [comment]
I have to confirm that unfortunately this is still not working.

**Comment by KevinRoebert** [comment]
@paoloantinori That is strange. I can open and use Slack with this PR. What operating system are you using?

**Comment by paoloantinori** [comment]
Linux. Fedora 40, and I'm testing the `.rpm` package

**Comment by paoloantinori** [comment]
There might be differences with instances.
If I try `redhat.slack.com` I get an instance error message.
If I try `kubernetes.slack.com` it offers me the chance to login, but then fails telling me my browser is not supported.

There might be instances where the whole thing just works.

**Comment by KevinRoebert** [comment]
> There might be differences with instances. If I try `redhat.slack.com` I get an instant error message. If I try `kubernetes.slack.com` it offers me the chance to login, but then fails telling me my browser is not supported.
> 
> There might be instances where the whole thing just works.

Do I miss something?

https://github.com/user-attachments/assets/7dab93f0-b1a6-4dac-8edd-e971d4c912fc

**Comment by paoloantinori** [comment]
Clearing `~/.config/LibreRambox` fixes the issue and I can now login.

unfortunately, it brings back an old bug that went away on its own but it's now back:
https://github.com/LibreRambox/LibreRambox/issues/5

I honestly don't remember if I had to tweak anything at config level to allow me to use workspaces

**Comment by paoloantinori** [comment]
Found the correct config that involved a specific internal URL. All working from my side, thank you!
