### ISSUE TITLE
#7 breaks opening of some links

### ISSUE THREAD

**Issue by KevinRoebert** [LibreRambox/LibreRambox#8]
### Steps to reproduce

1. Click on About **LibreRambox**
2. Click on the **GitHub** Link
3. See error

### Expected behavior

Link should open.

### Actual behavior

![Bildschirmfoto 2023-09-29 um 10 52 52](https://github.com/LibreRambox/LibreRambox/assets/28713602/3e571144-dbbc-480b-8801-49cd4ff56582)

### ENVIRONMENT

> LibreRambox: v0.10.0

> OS: MacOS Ventura 13.6

> Arch: x64

**Comment by wolfposd** [comment]
https://github.com/LibreRambox/LibreRambox/blob/master/electron/main.js#L151C2-L154C5
